// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWjDpAfDEJYeKu_wUCkebFgQprRV_aMm8',
    appId: '1:582986837014:web:82040a9a222bc16e555937',
    messagingSenderId: '582986837014',
    projectId: 'fir-learning-ae69d',
    authDomain: 'fir-learning-ae69d.firebaseapp.com',
    storageBucket: 'fir-learning-ae69d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIrD8iy3q5Ahx9OYqZSpUm6OOjP6ErOQ',
    appId: '1:582986837014:android:de8a6e36e86aec07555937',
    messagingSenderId: '582986837014',
    projectId: 'fir-learning-ae69d',
    storageBucket: 'fir-learning-ae69d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBwynLs-sjZtXUzBnFVAvA4I01qC9p3gg',
    appId: '1:582986837014:ios:5ca9c7337e0ff379555937',
    messagingSenderId: '582986837014',
    projectId: 'fir-learning-ae69d',
    storageBucket: 'fir-learning-ae69d.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBwynLs-sjZtXUzBnFVAvA4I01qC9p3gg',
    appId: '1:582986837014:ios:5ca9c7337e0ff379555937',
    messagingSenderId: '582986837014',
    projectId: 'fir-learning-ae69d',
    storageBucket: 'fir-learning-ae69d.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithFirebase',
  );
}
